// Main reducer action types

export const SET_SIDEBAR_SHOW = "SET_SIDEBAR_SHOW";
export const SET_GLOBALLY_UPDATE_STATE = "SET_GLOBALLY_UPDATE_STATE";
export const SET_NOTIFICATIONS_SHOW = "SET_NOTIFICATIONS_SHOW";
export const USER_LOGIN = "USER_LOGIN";
export const AUTH_CHECKER = "AUTH_CHECKER";
export const USER_LOGOUT = "USER_LOGOUT";
export const SET_SESSION_USER = "SET_SESSION_USER";
export const SET_APARTMENT_USERS = "SET_APARTMENT_USERS";
export const SET_APARTMENT_USERS_UPDATE_STATE = "SET_APARTMENT_USERS_UPDATE_STATE";
export const SET_USER_PROFILE = "SET_USER_PROFILE";
export const SET_MESSAGE = "SET_MESSAGE";
export const DELETE_MESSAGE = "DELETE_MESSAGE";

// Desktop reducer action types

export const SET_APARTMENT_ID = "SET_APARTMENT_ID";
export const SET_APARTMENT_NEWS = "SET_APARTMENT_NEWS";
export const SET_APARTMENT_TASKS = "SET_APARTMENT_TASKS";
export const SET_APARTMENT_MY_TASKS = "SET_APARTMENT_MY_TASKS";

// HousesInMap reducer action types

export const SET_ORGANIZATIONS_HOUSES_MAP = "SET_ORGANIZATIONS_HOUSES_MAPS";
export const SET_ORGANIZATION_INFO = "SET_ORGANIZATION_INFO";
export const SET_FILTERED_HOUSES_MAP = "SET_FILTERED_HOUSES_MAP";
export const SET_SERVICE_ORGANIZATIONS = "SET_SERVICE_ORGANIZATIONS";
export const SET_APARTMENT_HOUSE_ONE = "SET_APARTMENT_HOUSE_ONE";
export const SET_HOUSE_ORGANIZATION_REVIEWS = "SET_HOUSE_ORGANIZATION_REVIEWS";
export const SET_HOUSE_ORGANIZATION_CHANGES = "SET_HOUSE_ORGANIZATION_CHANGES";
export const SET_HOUSE_ORGANIZATION_USER_REVIEWS = "SET_HOUSE_ORGANIZATION_USER_REVIEWS";
export const SET_UPDATE_REVIEWS = "SET_UPDATE_REVIEWS";
export const SET_ORGANIZATION_UPDATING_INFO = "SET_ORGANIZATION_UPDATING_INFO";
export const SET_LOCALITY = "SET_LOCALITY";
export const SET_ACTIVE_LOCALITY = "SET_ACTIVE_LOCALITY";

// Organization reducer action types

export const SET_ORGANIZATIONS = "SET_ORGANIZATIONS";
export const SET_ORGANIZATIONS_TYPES = "SET_ORGANIZATIONS_TYPES";
export const SET_ORGANIZATIONS_UPDATE_STATE = "SET_ORGANIZATIONS_UPDATE_STATE";
export const SET_SEARCH_ORGANIZATIONS_TYPE = "SET_SEARCH_ORGANIZATIONS_TYPE";

// Chat reducer action types

export const SET_CHATS_VIEW = "SET_CHATS_VIEW";
export const SET_CURRENT_CHAT_INFO = "SET_CURRENT_CHAT_ID";
export const SET_SELECTED_MESSAGES = "SET_SELECTED_MESSAGES";
export const SET_CHAT_CONTENT_SCROLL = "SET_CHAT_CONTENT_SCROLL";
export const SET_CHAT_REPLY_MESSAGE = "SET_CHAT_REPLY_MESSAGE";

// News reducer action types

export const SET_NEWS_LIST = "SET_NEWS_LIST";
export const SET_NEWS_ID = "SET_NEWS_ID";
export const SET_NEWS_DETAIL = "SET_NEWS_DETAIL";
export const SET_MORE_NEWS = "SET_MORE_NEWS";

// VideoObserving reducer action types

export const SET_CAMERAS_LIST = "SET_CAMERAS_LIST";
export const SET_CAMERA_PAGE = "SET_CAMERA_PAGE";
export const SET_LIST_VALID_STATE = "SET_LIST_VALID_STATE";
export const SET_CAMERA_CATEGORY = "SET_CAMERA_CATEGORY";
export const SET_CAMERA_CATEGORIES = "SET_CAMERA_CATEGORIES";

// Meters reducer action types

export const SET_METERS_LIST = "SET_METERS_LIST";
export const SET_METERS_RECORDS = "SET_METERS_RECORDS";
export const SET_METERS_FILTER_TYPE = "SET_METERS_FILTER_TYPE";

// Tasks reducer action types

export const SET_TASKS_LIST = "SET_TASKS_LIST";
export const SET_MY_TASKS_LIST = "SET_MY_TASKS_LIST";
export const SET_LIST_COUNT = "SET_LIST_COUNT";
export const SET_SEARCH_TASK_QUERY = "SET_SEARCH_TASK_QUERY";
export const SET_SEARCH_TASK_STATUS = "SET_SEARCH_TASK_STATUS";
export const SET_SEARCH_TASK_DATE = "SET_SEARCH_TASK_DATE";
export const SET_SEARCH_TASK_URGENTLY = "SET_SEARCH_TASK_URGENTLY";
export const SET_TASK = "SET_TASK";
export const SET_TASK_LOGS = "SET_TASK_LOGS";
export const SET_APARTMENT_HOUSE_ID = "SET_APARTMENT_HOUSE_ID";

// Polls reducer action types

export const SET_CURRENT_POLLS = "SET_CURRENT_POLLS";
export const SET_PAST_POLLS = "SET_PAST_POLLS";
export const SET_SEARCH_POLL_DATE = "SET_SEARCH_POLL_DATE";
export const SET_POLLS_UPDATE_STATE = "SET_POLLS_UPDATE_STATE";
export const SET_SEARCH_POLL_TYPE = "SET_SEARCH_POLL_TYPE";
export const SET_SEARCH_POLL_QUERY = "SET_SEARCH_POLL_QUERY";
export const SET_POLL_ONE = "SET_POLL_ONE";
export const SET_POLL_ONE_UPDATE_STATE = "SET_POLL_ONE_UPDATE_STATE";

// Apartments reducer action types

export const SET_APARTMENT_HOUSES = "SET_APARTMENT_HOUSES";
export const SET_APARTMENT_HOUSE_INFO = "SET_APARTMENT_HOUSE_INFO";
export const SET_APARTMENT_HOUSE_ORGANIZATION_REVIEWS = "SET_APARTMENT_HOUSE_ORGANIZATION_REVIEWS";
export const SET_APARTMENT_HOUSE_USERS = "SET_APARTMENT_HOUSE_USERS";
export const SET_APARTMENT_HOUSE_SENIORS = "SET_APARTMENT_HOUSE_SENIORS";
export const SET_APARTMENT_HOUSE_WORKERS = "SET_APARTMENT_HOUSE_WORKERS";
export const SET_APARTMENT_HOUSE_FILTER_NUMBER = "SET_APARTMENT_HOUSE_FILTER_NUMBER";
export const SET_APARTMENT_FILTER_CITY = "SET_APARTMENT_FILTER_CITY";

// Documents reducer action types

export const SET_DOCUMENTS = "SET_DOCUMENTS";
export const SET_DOCUMENTS_TYPES = "SET_DOCUMENTS_TYPES";
export const SET_DOCUMENTS_TARGET_GROUPS_TYPES = "SET_DOCUMENTS_TARGET_GROUPS_TYPES";
export const SET_DOCUMENTS_UPDATE_STATE = "SET_DOCUMENTS_UPDATE_STATE";